import { State } from "./types";

const now = new Date();
const d = (offset: number) =>
  new Date(now.getTime() + offset * 24 * 60 * 60 * 1000)
    .toISOString()
    .slice(0, 10);

export const initialState: State = {
  objectives: [
    {
      id: "o1",
      name: "Zwiększyć konwersję checkout",
      owner: "Anna",
      start: d(-30),
      end: d(60),
      krIds: ["kr1", "kr2"],
    },
    {
      id: "o2",
      name: "Zmniejszyć porzucenia onboardingu",
      owner: "Piotr",
      start: d(-30),
      end: d(60),
      krIds: ["kr3"],
    },
    {
      id: "o3",
      name: "Obniżyć koszty infra",
      owner: "Marta",
      start: d(-30),
      end: d(60),
      krIds: ["kr4"],
    },
    {
      id: "o4",
      name: "Zwiększyć szybkość releasów",
      owner: "Jan",
      start: d(-30),
      end: d(60),
      krIds: ["kr5"],
    },
  ],
  krs: [
    {
      id: "kr1",
      objectiveId: "o1",
      name: "Konwersja +15%",
      unit: "pct",
      target: 15,
      current: 6,
      due: d(60),
      owner: "Anna",
      confidence: 0.68,
      epicIds: ["e1", "e2"],
      issueIds: ["i1", "i2", "i3"],
    },
    {
      id: "kr2",
      objectiveId: "o1",
      name: "Błędy płatności -30%",
      unit: "pct",
      target: 30,
      current: 10,
      due: d(60),
      owner: "Anna",
      confidence: 0.55,
      epicIds: ["e2"],
      issueIds: ["i4", "i5"],
    },
    {
      id: "kr3",
      objectiveId: "o2",
      name: "Onboarding drop -20%",
      unit: "pct",
      target: 20,
      current: 8,
      due: d(60),
      owner: "Piotr",
      confidence: 0.74,
      epicIds: ["e3"],
      issueIds: ["i6"],
    },
    {
      id: "kr4",
      objectiveId: "o3",
      name: "Infra cost -10%",
      unit: "pct",
      target: 10,
      current: 3,
      due: d(60),
      owner: "Marta",
      confidence: 0.62,
      epicIds: ["e4"],
      issueIds: [],
    },
    {
      id: "kr5",
      objectiveId: "o4",
      name: "Release velocity +40%",
      unit: "pct",
      target: 40,
      current: 22,
      due: d(60),
      owner: "Jan",
      confidence: 0.79,
      epicIds: ["e5"],
      issueIds: ["i7"],
    },
  ],
  epics: [
    {
      id: "e1",
      name: "Checkout UX revamp",
      team: "Frontend",
      issueIds: ["i1", "i2"],
      krIds: ["kr1"],
    },
    {
      id: "e2",
      name: "Payment reliability",
      team: "Backend",
      issueIds: ["i3", "i4", "i5"],
      krIds: ["kr1", "kr2"],
    },
    {
      id: "e3",
      name: "Onboarding simplification",
      team: "Frontend",
      issueIds: ["i6"],
      krIds: ["kr3"],
    },
    {
      id: "e4",
      name: "Infra autoscaling",
      team: "Platform",
      issueIds: [],
      krIds: ["kr4"],
    },
    {
      id: "e5",
      name: "CI/CD improvements",
      team: "Platform",
      issueIds: ["i7"],
      krIds: ["kr5"],
    },
  ],
  issues: [
    {
      id: "i1",
      title: "Simplify checkout form",
      assignee: "Ola",
      status: "in_progress",
      priority: "P2",
      storyPoints: 3,
      epicId: "e1",
      krIds: ["kr1"],
    },
    {
      id: "i2",
      title: "Add express payment",
      assignee: "Kamil",
      status: "todo",
      priority: "P1",
      storyPoints: 5,
      epicId: "e1",
      krIds: ["kr1"],
    },
    {
      id: "i3",
      title: "Retry logic on gateway errors",
      assignee: "Ewa",
      status: "in_review",
      priority: "P1",
      storyPoints: 3,
      epicId: "e2",
      krIds: ["kr1"],
    },
    {
      id: "i4",
      title: "Circuit breaker for PSP",
      assignee: "Michał",
      status: "todo",
      priority: "P0",
      storyPoints: 8,
      epicId: "e2",
      krIds: ["kr2"],
    },
    {
      id: "i5",
      title: "Alerting for declines",
      assignee: "Aga",
      status: "todo",
      priority: "P2",
      storyPoints: 3,
      epicId: "e2",
      krIds: ["kr2"],
    },
    {
      id: "i6",
      title: "Reduce fields in signup",
      assignee: "Tomek",
      status: "in_progress",
      priority: "P2",
      storyPoints: 5,
      epicId: "e3",
      krIds: ["kr3"],
    },
    {
      id: "i7",
      title: "Parallelize e2e tests",
      assignee: "Kuba",
      status: "in_progress",
      priority: "P2",
      storyPoints: 5,
      epicId: "e5",
      krIds: ["kr5"],
    },
  ],
  gates: [
    {
      id: "g1",
      epicId: "e1",
      name: "coverage",
      metric: "coverage",
      threshold: 80,
      status: "pass",
      updatedAt: new Date().toISOString(),
    },
    {
      id: "g2",
      epicId: "e2",
      name: "tests_pass",
      metric: "tests_pass",
      threshold: 95,
      status: "fail",
      updatedAt: new Date().toISOString(),
    },
    {
      id: "g3",
      epicId: "e2",
      name: "lint",
      metric: "lint",
      threshold: 100,
      status: "pass",
      updatedAt: new Date().toISOString(),
    },
    {
      id: "g4",
      epicId: "e5",
      name: "approvals",
      metric: "approvals",
      threshold: 2,
      status: "pass",
      updatedAt: new Date().toISOString(),
    },
  ],
  dora: [
    { date: d(-7), leadTimeH: 48, deploys: 6, changeFailRate: 0.15, mttrH: 3 },
    {
      date: d(-6),
      leadTimeH: 44,
      deploys: 7,
      changeFailRate: 0.12,
      mttrH: 2.5,
    },
    { date: d(-5), leadTimeH: 50, deploys: 6, changeFailRate: 0.18, mttrH: 4 },
    { date: d(-4), leadTimeH: 42, deploys: 8, changeFailRate: 0.1, mttrH: 2 },
    {
      date: d(-3),
      leadTimeH: 41,
      deploys: 8,
      changeFailRate: 0.09,
      mttrH: 1.8,
    },
    {
      date: d(-2),
      leadTimeH: 40,
      deploys: 9,
      changeFailRate: 0.08,
      mttrH: 1.5,
    },
    {
      date: d(-1),
      leadTimeH: 39,
      deploys: 9,
      changeFailRate: 0.07,
      mttrH: 1.4,
    },
  ],
  activities: [],
  settings: {
    healthWeights: { outcome: 0.5, delivery: 0.3, quality: 0.2 },
    thresholds: {
      confidenceAtRisk: 0.74,
      confidenceOff: 0.5,
      gatePassMin: 0.9,
      orphanWorkMaxPct: 0.15,
    },
  },
};
