// Mock data for Syzio demo
import type { User, Issue, Sprint, Team, Activity, Comment, AutomationRule } from "./types"

export const mockUsers: User[] = [
  {
    id: "u1",
    name: "Anna Kowalska",
    email: "anna@syzio.demo",
    role: "admin",
    avatarUrl: "/woman-developer.png",
  },
  {
    id: "u2",
    name: "Jan Nowak",
    email: "jan@syzio.demo",
    role: "member",
    avatarUrl: "/man-developer.png",
  },
  {
    id: "u3",
    name: "Maria Wiśniewska",
    email: "maria@syzio.demo",
    role: "member",
    avatarUrl: "/woman-designer.png",
  },
  {
    id: "u4",
    name: "Piotr Lewandowski",
    email: "piotr@syzio.demo",
    role: "member",
    avatarUrl: "/man-engineer.png",
  },
]

export const mockSprints: Sprint[] = [
  {
    id: "s1",
    name: "Sprint 24 - Q1 Features",
    goal: "Deliver core dashboard improvements and user management",
    start: "2025-01-06",
    end: "2025-01-20",
    status: "active",
    issueIds: ["i1", "i2", "i3", "i4", "i5"],
  },
  {
    id: "s2",
    name: "Sprint 25 - Performance",
    goal: "Optimize application performance and fix critical bugs",
    start: "2025-01-21",
    end: "2025-02-04",
    status: "planned",
    issueIds: [],
  },
]

export const mockIssues: Issue[] = [
  {
    id: "i1",
    key: "TASK-101",
    title: "Fix critical login bug affecting mobile users",
    description: "Users on mobile devices cannot log in due to OAuth redirect issue",
    priority: "P0",
    status: "in_progress",
    assigneeId: "u1",
    sprintId: "s1",
    storyPoints: 5,
    labels: ["bug", "mobile", "auth"],
    favorite: true,
    createdAt: "2025-01-07T10:00:00Z",
    updatedAt: "2025-01-09T14:30:00Z",
    dueAt: "2025-01-10T23:59:59Z",
  },
  {
    id: "i2",
    key: "TASK-102",
    title: "Implement new dashboard analytics widget",
    description: "Add real-time analytics widget to the main dashboard",
    priority: "P1",
    status: "in_review",
    assigneeId: "u2",
    sprintId: "s1",
    storyPoints: 8,
    labels: ["feature", "dashboard"],
    createdAt: "2025-01-06T09:00:00Z",
    updatedAt: "2025-01-09T16:00:00Z",
  },
  {
    id: "i3",
    key: "TASK-103",
    title: "Update user profile page design",
    description: "Redesign user profile page according to new brand guidelines",
    priority: "P2",
    status: "todo",
    assigneeId: "u3",
    sprintId: "s1",
    storyPoints: 3,
    labels: ["design", "ui"],
    createdAt: "2025-01-06T11:00:00Z",
    updatedAt: "2025-01-08T10:00:00Z",
  },
  {
    id: "i4",
    key: "TASK-104",
    title: "Optimize database queries for reports",
    description: "Improve performance of report generation queries",
    priority: "P1",
    status: "in_progress",
    assigneeId: "u4",
    sprintId: "s1",
    storyPoints: 5,
    labels: ["performance", "backend"],
    createdAt: "2025-01-07T08:00:00Z",
    updatedAt: "2025-01-09T12:00:00Z",
  },
  {
    id: "i5",
    key: "TASK-105",
    title: "Add export functionality to team reports",
    description: "Allow users to export team reports as PDF and CSV",
    priority: "P2",
    status: "todo",
    assigneeId: "u2",
    sprintId: "s1",
    storyPoints: 3,
    labels: ["feature", "reports"],
    createdAt: "2025-01-08T09:00:00Z",
    updatedAt: "2025-01-08T09:00:00Z",
  },
  {
    id: "i6",
    key: "TASK-106",
    title: "Research AI automation possibilities",
    description: "Investigate potential AI-powered automation features",
    priority: "P3",
    status: "todo",
    assigneeId: "u1",
    storyPoints: 2,
    labels: ["research", "ai"],
    createdAt: "2025-01-08T14:00:00Z",
    updatedAt: "2025-01-08T14:00:00Z",
  },
]

export const mockTeams: Team[] = [
  {
    id: "t1",
    name: "Frontend Team",
    memberIds: ["u1", "u3"],
    velocityHistory: [23, 28, 25, 30],
  },
  {
    id: "t2",
    name: "Backend Team",
    memberIds: ["u2", "u4"],
    velocityHistory: [20, 22, 24, 26],
  },
]

export const mockActivities: Activity[] = [
  {
    id: "a1",
    actorId: "u1",
    type: "issue_updated",
    targetType: "issue",
    targetId: "i1",
    createdAt: "2025-01-09T14:30:00Z",
    payload: { field: "status", from: "todo", to: "in_progress" },
  },
  {
    id: "a2",
    actorId: "u2",
    type: "issue_updated",
    targetType: "issue",
    targetId: "i2",
    createdAt: "2025-01-09T16:00:00Z",
    payload: { field: "status", from: "in_progress", to: "in_review" },
  },
  {
    id: "a3",
    actorId: "u3",
    type: "issue_created",
    targetType: "issue",
    targetId: "i3",
    createdAt: "2025-01-06T11:00:00Z",
  },
]

export const mockComments: Comment[] = [
    {
      id: "comment-1",
      issueId: "i1",
      userId: "u2",
      content: "I'll take a look at this right away.",
      createdAt: "2023-10-01T10:05:00Z",
    },
    {
      id: "comment-2",
      issueId: "i1",
      userId: "u1",
      content: "Thanks! Let me know if you need any logs.",
      createdAt: "2023-10-01T10:10:00Z",
    },
]

export const mockAutomationRules: AutomationRule[] = [
    {
      id: "1",
      name: "Auto-assign urgent issues",
      description: "Automatically assign P0 issues to team lead",
      active: true,
      lastRun: "2 hours ago",
      status: "success",
    },
    {
      id: "2",
      name: "Sprint completion reminder",
      description: "Send notification 2 days before sprint end",
      active: true,
      lastRun: "1 day ago",
      status: "success",
    },
    {
      id: "3",
      name: "Stale issue detection",
      description: "Flag issues with no activity for 7 days",
      active: false,
      lastRun: "5 days ago",
      status: "error",
    },
]
